### ISSUE TITLE
Limit the depth

### ISSUE THREAD

**Issue by ashkan-leo** [ScriptDevil/org-fs-tree#1]
Hi!
This is a great tool. Thank you for making it.
I use it for reading source code of a new project and taking notes. The tree for some of projects become really really large -- larger than 4.3 MB, and causes Emacs to crash.

Is there a way to limit the depth of the tree?

Thanks!
Ashkan

**Comment by ScriptDevil** [comment]
Seems simple enough - there is already a level in the recursive function that generates the tree - will try to get to it by EOW

**Comment by ScriptDevil** [comment]
done: https://github.com/ScriptDevil/org-fs-tree/commit/0dd708715d423b78fed7a1cc6b7d618d74e25bed
